Fatal error: exception Failure("illegal actual argument in call to foo: found Int, expected Bool in IntLit(42)")
